name: Deploy site to Liteyuki PaaS

on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
  statuses: write

concurrency:
  group: pages
  cancel-in-progress: false

env:
  MELI_SITE: "9f8927f7-5daa-4515-b754-076a41b6a4f7"

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要

      - name: "发布"
        run: |
          npx -p "@getmeli/cli" meli upload . \
            --url "https://pages.liteyuki.icu" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA"
        env:
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}